# This file was generated by the Securial engine.
# You can customize logging behavior here.

Securial.configure do |config|
  # Enable or disable logging to file
  config.log_to_file = false

  # Enable or disable logging to STDOUT
  config.log_to_stdout = false

  # Set log level for file logger: :debug, :info, :warn, :error, :fatal, or :unknown
  config.file_log_level = :info

  # Set log level for stdout logger
  config.stdout_log_level = :info

  # Set the role for admin users
  config.admin_role = :admin

  # Set the role for regular users
  config.user_role = :user
end
